# Generated by Django 3.2.16 on 2022-12-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20221228_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='banner',
            field=models.ImageField(blank=True, help_text='Please add (Height 315px Width 1140px) JPG PNG files for banner images. Optimize your image before it uploads', max_length=255, null=True, upload_to='organization_banners'),
        ),
        migrations.AddField(
            model_name='organization',
            name='url',
            field=models.CharField(db_index=True, default='https://github.com/', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HistoricalOrganization',
        ),
    ]
